---
- name: Install Git on RedHat-based systems
  yum:
    name: git
    state: present
  when: ansible_os_family == "RedHat"
  become: yes
  become_user: root

- name: Install Git on Debian-based systems
  apt:
    name: git
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"
  become: yes
  become_user: root

- name: Install expect on RedHat-based systems
  yum:
    name: expect
    state: present
  when: ansible_os_family == "RedHat"
  become: yes
  become_user: root

- name: Install expect on Debian-based systems
  apt:
    name: expect
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"
  become: yes
  become_user: root

- name: Ensure .ssh directory exists
  file:
    path: "/home/ec2-user/.ssh"
    state: directory
    mode: '0700'
    owner: ec2-user
    group: ec2-user
  become: yes

- name: Copy SSH private key to remote server
  copy:
    src: "{{ local_ssh_key_path }}"
    dest: "/home/ec2-user/.ssh/id_rsa"
    mode: '0600'
    owner: ec2-user
    group: ec2-user
  become: yes

- name: Copy SSH public key to remote server
  copy:
    src: "{{ local_ssh_key_path }}.pub"
    dest: "/home/ec2-user/.ssh/id_rsa.pub"
    mode: '0644'
    owner: ec2-user
    group: ec2-user
  become: yes

- name: Configure Git user name
  git_config:
    name: user.name
    value: "{{ git_user_name }}"
    scope: global
  become: yes
  become_user: ec2-user

- name: Configure Git user email
  git_config:
    name: user.email
    value: "{{ git_user_email }}"
    scope: global
  become: yes
  become_user: ec2-user

- name: Verify SSH keys are copied
  shell: ls -la /home/ec2-user/.ssh
  register: ssh_dir_contents
  become: yes

- name: Display SSH directory contents
  debug:
    var: ssh_dir_contents.stdout_lines

- name: Add SSH key to ssh-agent using expect
  shell: |
    expect -c '
    spawn ssh-agent bash
    expect "Agent pid"
    spawn ssh-add /home/ec2-user/.ssh/id_rsa
    expect "Enter passphrase"
    send "{{ ssh_key_passphrase }}\r"
    expect eof
    '
  args:
    executable: /bin/bash
  become: yes
  become_user: ec2-user